# Generated by Django 3.2.9 on 2022-01-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(editable=False, max_length=512, verbose_name='密码'),
        ),
    ]
