# Generated by Django 3.2.9 on 2022-03-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_friend_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['create_date'], 'verbose_name': '好友', 'verbose_name_plural': '好友列表'},
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='friends',
        ),
    ]
