# Generated by Django 3.2 on 2022-05-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_friend_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('title', models.CharField(max_length=512, null=True, verbose_name='标题')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='作者')),
                ('friend_like_list', models.ManyToManyField(related_name='friend_like_list', to='user.User', verbose_name='好友点赞列表')),
                ('friend_view_list', models.ManyToManyField(related_name='friend_view_list', to='user.User', verbose_name='好友查看列表')),
            ],
            options={
                'verbose_name': '动态消息',
                'verbose_name_plural': '动态消息数据模型',
                'ordering': ['create_date'],
            },
            bases=('user.basemodel',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('file_name', models.CharField(max_length=256, verbose_name='文件名称')),
                ('file_content', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件内容')),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.option', verbose_name='文件类型')),
                ('related_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.news', verbose_name='关联动态消息')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件数据',
                'ordering': ['create_date'],
            },
            bases=('user.basemodel',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('content', models.CharField(max_length=256, verbose_name='回复内容')),
                ('aims_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aims_user', to='user.user', verbose_name='目标用户')),
                ('comment_news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.news', verbose_name='关联动态消息')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='user.user', verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '用户评论',
            },
            bases=('user.basemodel',),
        ),
    ]
