# Generated by Django 3.2 on 2022-09-05 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_comment_file_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('accept_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accept_user', to='user.user', verbose_name='接收用户')),
                ('send_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to='user.user', verbose_name='发送用户')),
            ],
            options={
                'verbose_name': '聊天',
            },
            bases=('user.basemodel',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('content', models.CharField(max_length=512, verbose_name='消息内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.option', verbose_name='消息类型')),
                ('msg_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.chat', verbose_name='聊天')),
            ],
            options={
                'verbose_name': '聊天信息',
            },
            bases=('user.basemodel',),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.basemodel')),
                ('users', models.ManyToManyField(to='user.User')),
            ],
            options={
                'verbose_name': '群聊',
            },
            bases=('user.basemodel',),
        ),
    ]
